"""API request and response schemas.

Note the split between :class:`SubmitRequest` (what a client may send) and
:class:`AnalysisRequest` (what the pipeline runs): clients reference a ``run_id``
whose input files the server placed itself, and never a server-side path. The
path-carrying request is internal only.
"""

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, model_validator


class RunStatus(str, Enum):
    """Lifecycle states for an analysis run."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class UploadResponse(BaseModel):
    """Response returned after a successful file upload."""

    run_id: str
    message: str
    files: Dict[str, str] = Field(
        description="Logical role -> stored filename for each input file."
    )
    submit_url: str


class ErrorResponse(BaseModel):
    """Standard error envelope."""

    detail: str
    error_code: Optional[str] = None


class AnalysisParameters(BaseModel):
    """Windowing and threshold parameters shared by every analysis run."""

    stride: int = Field(default=1, ge=1)
    start_frame: Optional[int] = Field(default=None, ge=0)
    end_frame: Optional[int] = Field(default=None, ge=0)

    hbond_cutoff: float = Field(default=3.5, ge=2.0, le=5.0)
    contact_cutoff: float = Field(default=8.0, ge=3.0, le=15.0)
    salt_bridge_cutoff: float = Field(default=4.0, ge=2.0, le=8.0)

    @model_validator(mode="after")
    def validate_frame_window(self) -> "AnalysisParameters":
        if (
            self.start_frame is not None
            and self.end_frame is not None
            and self.end_frame <= self.start_frame
        ):
            raise ValueError("end_frame must be greater than start_frame")
        return self

    def module_parameters(self) -> Dict[str, Any]:
        """Parameters recorded in the RunCard for reproducibility."""
        return {
            "stride": self.stride,
            "start_frame": self.start_frame,
            "end_frame": self.end_frame,
            "hbond_cutoff": self.hbond_cutoff,
            "contact_cutoff": self.contact_cutoff,
            "salt_bridge_cutoff": self.salt_bridge_cutoff,
        }


class SubmitRequest(AnalysisParameters):
    """Client request to analyse the files already uploaded for ``run_id``."""

    run_id: str = Field(min_length=1, description="Run id returned by /upload.")


class AnalysisRequest(AnalysisParameters):
    """Internal pipeline request: resolved input paths plus parameters."""

    run_id: Optional[str] = Field(
        None, description="Run id; generated by the orchestrator when omitted."
    )
    topology_file: str = Field(description="Server-side path to the topology file.")
    trajectory_file: str = Field(description="Server-side path to the trajectory file.")


class AnalysisResponse(BaseModel):
    """Response returned after submitting an analysis run."""

    run_id: str
    message: str
    status_url: str


class StatusResponse(BaseModel):
    """Current state of an analysis run."""

    run_id: str
    status: RunStatus
    message: str
    current_module: Optional[str] = None
    progress_percent: float = Field(default=0.0, ge=0.0, le=100.0)
    results_url: Optional[str] = None


class DemoDatasetInfo(BaseModel):
    """A preloaded dataset a caller can analyse without uploading anything."""

    key: str
    name: str
    description: str
    n_frames: int


class DemoRunResponse(BaseModel):
    """Result of the zero-setup demo path."""

    run_id: str
    dataset: str
    caveat: str
    report_url: str
    report_html_url: str
    review_status: str
    grounding_passed: bool
    n_verified_claims: int
    generator: str
    seconds: float


class DemoDatasetList(BaseModel):
    datasets: List[DemoDatasetInfo]
